language: node_js
node_js: node
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: YrnNnXmdLfjAgiu15TaKW0u8lE2jUakWvqEvnAZpg1urrE9cMrgQeQBzTC7D8rIhDbzgJlA3JHKArf88BMOQe7pMm6xo4wPQnRH85HlZpLICTz7JXjmQTeMLboPMS81tzjVYo+gDD+iGK/BTsAEK0aY3Lxra+OvDz7MG2sEc1XuctOp3WcSYTpbM+34tniiieonh2jrgUgSIt3Bz/kH4d8uXtY9oq1GsM7ooq2g9QJRwC38J3NzeL4ADQLVhEIyl9+BA/N5VHFBXCjgKHvmy4+EdADKYs3dqQMNsMN4aPWdZ4gDCYi33ZkZPDW92F/kA5gl7ReI01HaD2Artsx9+nAmOPjORaU1UeoyQ8rICUNEvsWkseFcuLlcf9ehL5JFlrcKc3Art4htZc95XzxxWWT+Ih/FyqvLZdzWvqu0qvlxenlaIfbneV/5ra4/8fOyBcKsylk93YCdE01h/zZjLiWq6S1wTsn+vffIKksvWdgVFC/iiAxLiXaNIWdZf0tMTC6fnlqGKd/n+LsUPNkYfeaMOdX2vV2Gcm0YIQvfCQuL58hLNWdlNN/WKB4rzk5aV8uOZpvB+iRxc131OEtaalSbHjND5BL9b2x1Yqh76VKPemjVycgz2HqKz4ZYG3uLZcTSXiFh01XDCp36N8uZXTRy5HjmhaOHbMOd8nL4/tcU=
  on:
    tags: true
    repo: canjs/can-define-class
